version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 1200
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 1200

      runas: root
