# Generated by Django 5.1.2 on 2024-10-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_designation',
            new_name='designation',
        ),
    ]
